### PR TITLE
Add loop feature in Executor

### PR DESCRIPTION
**Pull request by guiled**
### What was a problem?
Need a loop visit on same child

### How this PR fixes the problem?
Add a return value to specify the executor to visit the child again

### CODE REVIEW

**Comment by SerafimArts** [comment]
Is there an example of when such functionality may be required? I do not recall such a case when it would be required to "visit" all nodes siblings again.

**Comment by SerafimArts** [comment]
In any case, I don’t see problems why this functionality was not present, except for unnecessarily re-complicating the existing code (which is already not very good) =)

**Comment by guiled** [comment]
I use phplrt with Lua grammar in order to execute a specific script with php. As this script language has loop controls, I was searching for a solution to do it without "loop" in executor.
I have a Node "WhileLoop" for example that have children that are visited. Then on WhileLoop::leave it does the test : all its children must be revisited or not.
I have considered a solution that "clones" children as much as it loops but I must admit it's a really crappy solution…

**Comment by guiled** [comment]
I use phplrt in order to execute a specific script with php. As this script language has loop controls, I was searching for a solution to do it without "loop" in executor.
I have a Node "WhileLoop" for example that have children that are visited. Then on WhileLoop::leave it does the test : all its children must be revisited or not.
I have considered a solution that "clones" children as much as it loops but I must admit it's a really crappy solution…

**Comment by guiled** [comment]
If you think it should be done in an other way, I am listening, as I am quite n00b with phplrt !

**Comment by SerafimArts** [comment]
Either transpiling or an interpreter is used for this. In addition, you can convert AST nodes to a set of opcodes that will already be played by your virtual machine, like this: https://gist.github.com/SerafimArts/ce7e0ca28b325e4c8794aede4ffd8a74

**Pull request merged**
